### PR TITLE
fix invalid io format in error logger handler

### LINKED ISSUE #45: a call to `erllambda:message/2` with empty `Values` list brakes logging
the following code:
```
handle(_Event, _Context) ->
    erllambda:message("Starting logs test"),
    erllambda:message("This line brakes logging", []),
    erllambda:message("This and any further logs are not printed"),
    {ok, "done"}.
```
gives the following log at the first invoke:
```
START RequestId: c51bef51-f4cf-11e8-a390-f701c3391a2f Version: $LATEST
[context@36312 aid="c51bef51-f4cf-11e8-a390-f701c3391a2f"] 127.0.0.1 - - [30/Nov/2018:18:43:05 -0000] Invoke Next
Next returns, in invoke 1543603385146
Starting logs test
END RequestId: c51bef51-f4cf-11e8-a390-f701c3391a2f
REPORT RequestId: c51bef51-f4cf-11e8-a390-f701c3391a2f  Init Duration: 696.26 ms    Duration: 1.97 ms   Billed Duration: 700 ms     Memory Size: 2048 MB    Max Memory Used: 75 MB
```
and the following log at further invokes:
```
START RequestId: e5ea113c-f4cf-11e8-8c3c-75c4192a8db6 Version: $LATEST
END RequestId: e5ea113c-f4cf-11e8-8c3c-75c4192a8db6
REPORT RequestId: e5ea113c-f4cf-11e8-8c3c-75c4192a8db6  Duration: 9.09 ms   Billed Duration: 100 ms     Memory Size: 2048 MB    Max Memory Used: 75 MB 
```

### PR DESCRIPTION
**Pull request by velimir**
fixes #45 

fyi @key-master

### CODE REVIEW

File: test/erllambda_logging_handler.erl [hunk 1]
```diff
@@ -0,0 +1,14 @@
...
+%% API
+-export([handle/2]).
+
+%%%===================================================================
+%%% API
+%%%===================================================================
+
+handle(_Event, _Context) ->
+    erllambda:message("Starting logs test"),
+    erllambda:message("This line should not brake logging", []),
```
Comment (codeadict) [inline test/erllambda_logging_handler.erl]: brake//break
